In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url1 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2022/jrubik7dee196ae088a75d2d7a295902b8c75056a9ed80.html"

response = requests.get(url1)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df1 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df1.to_csv("datos_irpf_provincia_2022.csv", index=False)

print(df1.shape)
df1.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_17076\3412003727.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,22898072,30400,7603,547838428,25700185,696112475,25763465,108398218,561969473
1,Andalucía,4092833,25203,785,81661113,4645442,103149809,3932732,13867280,85352146
2,Almería,370379,22508,103,6511399,331433,8336364,330075,1036104,6970325
3,Cádiz,562798,25902,45,11841966,698222,14577458,555339,1924752,12097599
4,Córdoba,386797,23546,77,7328856,379168,9107421,352350,1165906,7589325
5,Granada,453968,25024,174,8924832,558057,11360100,414651,1518147,9427495
6,Huelva,268057,22377,80,5068279,244080,5998219,249318,730729,5018280
7,Jaén,323032,21493,97,5607936,365708,6942831,258682,792642,5891679
8,Málaga,791650,27131,103,16058917,926204,21478629,791928,3039060,17648470
9,Sevilla,936152,27078,106,20318928,1142571,25348786,980388,3659939,20708973
10,Aragón,747459,29174,731,17655179,717741,21806342,842748,3291709,17672235
11,Huesca,121558,27781,202,2635395,109026,3376952,130060,482228,2764717
12,Teruel,72031,25682,236,1510493,58754,1849874,73824,248955,1527126
13,Zaragoza,553870,29934,293,13509291,549961,16579516,638863,2560526,13380393
14,"Asturias, Principado de",544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
15,Asturias,544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
16,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
17,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
18,Canarias,1040463,26500,88,21535915,963342,27572081,1065029,3554245,22954535
19,"Palmas, Las",544461,27060,34,11481846,543560,14733217,572533,1967217,12194739
20,Santa Cruz de Tenerife,496002,25885,54,10054068,419782,12838864,492497,1587028,10759795
21,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
22,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
23,Castilla y León,1315508,27356,2246,29201935,1189149,35987001,1320984,5039844,29626893
24,Avila,80053,24144,248,1558956,71083,1932799,70524,238982,1623345
25,Burgos,205370,29130,371,4932443,178043,5982494,226624,868355,4887599
26,León,243383,26701,211,5344112,237618,6498599,238078,891865,5368804
27,Palencia,88330,26402,191,1895077,77415,2332075,85654,313250,1933213
28,Salamanca,174762,26967,362,3702090,149438,4712850,163044,662486,3887400
29,Segovia,82253,26887,209,1751821,69042,2211575,83244,303954,1824414
30,Soria,51757,26737,181,1127809,39781,1383810,51700,188801,1143331
31,Valladolid,302270,29393,225,7242635,293518,8884645,330112,1318205,7236540
32,Zamora,87330,23453,248,1646990,73210,2048155,72004,253945,1722247
33,Castilla-La Mancha,1030479,25393,914,21588501,989807,26167274,1083948,3343501,21740330
34,Albacete,199723,25094,87,4104721,184155,5011761,205902,639396,4166552
35,Ciudad Real,235515,24721,102,4779965,240654,5822234,231121,739768,4851449
36,Cuenca,99738,23331,239,1871316,94728,2326948,90946,264820,1971219
37,Guadalajara,140128,28923,284,3427273,158208,4052946,172907,560977,3319137
38,Toledo,355375,25194,202,7405225,312063,8953384,383072,1138540,7431972
39,Cataluña,3993108,35030,947,108683103,5165970,139880270,5154746,24340491,110388501
40,Barcelona,2978835,36641,311,84467979,4071368,109148574,3953639,19581687,85616039
41,Girona,384384,31571,221,9247410,373933,12135294,464705,1939809,9731105
42,Lleida,221818,28986,231,5060641,243338,6429724,256820,965993,5207049
43,Tarragona,408071,29815,184,9907072,477332,12166679,479583,1853002,9834308
44,Comunitat Valenciana,2585870,27707,543,56338421,2719773,71646195,2793065,10474446,58380403
45,Alicante/Alacant,887100,25456,141,17536991,765091,22582352,882981,3094756,18605190
46,Castellón/Castelló,316860,27646,135,7039549,333177,8759797,352830,1277389,7129944
47,Valencia/València,1381910,29165,267,31761881,1621505,40304046,1557254,6102302,32645268
48,Extremadura,520184,22563,388,9433400,504250,11737158,432645,1472913,9831784
49,Badajoz,321207,22487,165,5790577,310879,7223016,270832,900895,6051401

In [3]:
url2 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2019/jrubikf75972228ea46b0ae33eab3856fdab1bf0228bd6f.html"

response = requests.get(url2)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df2 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df2.to_csv("datos_irpf_provincia_2019.csv", index=False)

print(df2.shape)
df2.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_17076\898023753.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,21028886,28384,7605,470562625,21200359,596886538,22782294,86601299,487553470
1,Andalucía,3642683,23510,785,68559967,3588777,85639826,3400403,10545243,71696990
2,Almería,324413,21399,103,5364508,248592,6942160,277486,805141,5859690
3,Cádiz,495879,24497,45,10065861,534092,12147515,484276,1479154,10184236
4,Córdoba,351445,21879,77,6237946,279244,7689417,310722,900972,6477839
5,Granada,403795,23515,174,7462988,436874,9495286,359094,1166851,7969631
6,Huelva,239196,20972,80,4271150,192767,5016384,214973,563683,4237822
7,Jaén,299266,20266,97,4862900,295386,6065031,231584,633952,5199653
8,Málaga,696664,24712,103,13192984,724839,17216073,671936,2192832,14352482
9,Sevilla,832025,25321,106,17101629,876983,21067958,850333,2802658,17415638
10,Aragón,709124,27014,730,15514567,618104,19155971,770833,2642775,15742804
11,Huesca,114378,25513,202,2281885,92455,2918147,116248,378463,2423483
12,Teruel,69808,23356,236,1332318,48668,1630421,67621,198072,1364782
13,Zaragoza,524938,27827,292,11900364,476981,14607403,586964,2066240,11954539
14,"Asturias, Principado de",518251,27448,78,11745018,618827,14224740,542326,1932848,11750771
15,Asturias,518251,27448,78,11745018,618827,14224740,542326,1932848,11750771
16,"Balears, Illes",550891,29736,67,11815380,424500,16381423,613986,2446093,13321780
17,"Balears, Illes",550891,29736,67,11815380,424500,16381423,613986,2446093,13321780
18,Canarias,921343,25087,88,18144600,704173,23114132,917565,2906212,19291011
19,"Palmas, Las",486470,25636,34,9775256,405672,12470922,498211,1590144,10383031
20,Santa Cruz de Tenerife,434873,24474,54,8369344,298501,10643210,419354,1316068,8907979
21,Cantabria,288367,27010,102,6343259,266305,7788696,301861,1038805,6448198
22,Cantabria,288367,27010,102,6343259,266305,7788696,301861,1038805,6448198
23,Castilla y León,1255739,25317,2247,25805745,1026631,31791982,1210439,4004794,26577636
24,Avila,75233,21986,248,1342027,59267,1654101,62603,180290,1411262
25,Burgos,196484,26863,371,4365033,155396,5278110,208072,689535,4380593
26,León,232065,24547,211,4702779,209587,5696590,221730,692459,4782735
27,Palencia,85284,24470,191,1694358,66997,2086911,79906,250925,1756160
28,Salamanca,165975,24569,362,3259531,122914,4077792,146951,509831,3421085
29,Segovia,77101,24558,209,1505678,60991,1893425,73437,232434,1587615
30,Soria,49693,24315,183,986171,32785,1208266,46402,145964,1015933
31,Valladolid,289921,27941,224,6507730,258193,8100745,305912,1109177,6685773
32,Zamora,83983,21386,248,1442438,60501,1796043,65427,194180,1536480
33,Castilla-La Mancha,941007,23437,917,18206744,828438,22054851,936689,2584166,18534773
34,Albacete,183127,23259,87,3473078,151411,4259361,179175,503450,3577135
35,Ciudad Real,217194,22943,102,4078900,202483,4983065,202405,582523,4198216
36,Cuenca,92178,21238,239,1570459,80906,1957661,78637,203364,1675729
37,Guadalajara,125248,26814,285,2846285,135118,3358448,146747,429870,2781933
38,Toledo,323260,23190,204,6238022,258520,7496315,329727,864959,6301761
39,Cataluña,3726314,32423,947,94078938,4362934,120818837,4599771,19461348,96793858
40,Barcelona,2789987,33958,311,73400974,3470303,94742856,3542496,15770893,75464931
41,Girona,353080,28905,221,7852703,298261,10205639,409711,1487613,8308567
42,Lleida,206831,26684,231,4334358,203837,5519045,225300,760222,4533671
43,Tarragona,376416,27500,184,8490903,390533,10351296,422264,1442621,8486689
44,Comunitat Valenciana,2329246,25543,542,47251079,2060842,59495549,2403900,8037678,49055506
45,Alicante/Alacant,789491,23348,141,14596212,535840,18433368,754908,2307772,15371296
46,Castellón/Castelló,289546,25164,135,5918275,261685,7286093,306067,968993,6011202
47,Valencia/València,1250209,27016,266,26736593,1263316,33776087,1342925,4760913,27673007
48,Extremadura,486141,20926,388,8254480,398269,10173225,389009,1142532,8641888
49,Badajoz,297295,20916,165,5037883,243068,6218361,241436,694393,5282625

In [4]:
url3 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2016/jrubik3f9f09f705d8c4130e1303e412a2dd0af62da913.html"

response = requests.get(url3)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df3 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df3.to_csv("datos_irpf_provincia_2016.csv", index=False)

print(df3.shape)
df3.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_17076\1651912064.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df3 = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,19621728,25950,7591,408902664,16288184,509192179,19453744,70495199,419259939
1,Andalucía,3315566,21799,777,58651421,2681792,72274503,2825936,8525419,60925789
2,Almería,287451,19662,103,4474759,161826,5651733,223840,628208,4799810
3,Cádiz,450598,22894,44,8679045,405551,10316117,408109,1210278,8698009
4,Córdoba,333901,20251,75,5483952,203808,6761766,265268,762842,5733917
5,Granada,376244,21660,171,6515808,344726,8149356,305121,950014,6894419
6,Huelva,215673,19585,79,3606559,136392,4223919,176996,462976,3584051
7,Jaén,288760,19056,97,4295912,234669,5502672,197716,561406,4743605
8,Málaga,618263,22631,103,10979099,554602,13991631,540292,1676482,11775853
9,Sevilla,744676,23738,105,14616287,640218,17677309,708593,2273213,14696125
10,Aragón,682736,24742,731,13813357,501999,16892215,679284,2209329,14004000
11,Huesca,110622,22991,202,2001771,74860,2543286,101769,306205,2135332
12,Teruel,69329,21370,236,1220390,40101,1481577,61435,171101,1249086
13,Zaragoza,502785,25592,293,10591196,387037,12867352,516080,1732023,10619582
14,"Asturias, Principado de",507731,25502,78,10759438,532841,12948048,512702,1674878,10760848
15,Asturias,507731,25502,78,10759438,532841,12948048,512702,1674878,10760848
16,"Balears, Illes",502279,26790,67,9872426,312135,13455877,498101,1899398,11058660
17,"Balears, Illes",502279,26790,67,9872426,312135,13455877,498101,1899398,11058660
18,Canarias,814502,23243,88,15240285,491130,18931112,749023,2345358,15837487
19,"Palmas, Las",428939,23857,34,8213230,281385,10233276,408038,1284013,8541520
20,Santa Cruz de Tenerife,385563,22559,54,7027055,209745,8697836,340985,1061345,7295967
21,Cantabria,276160,24989,102,5675988,213333,6900877,268203,881770,5751121
22,Cantabria,276160,24989,102,5675988,213333,6900877,268203,881770,5751121
23,Castilla-La Mancha,899254,21449,919,15947144,654077,19288078,804674,2116245,16367831
24,Albacete,176136,21254,87,3054702,114791,3743531,154300,414227,3175044
25,Ciudad Real,211343,21062,102,3627016,179196,4451223,176123,484654,3790532
26,Cuenca,91647,19482,239,1414414,64790,1785460,68946,176726,1539808
27,Guadalajara,118159,24941,287,2514262,103476,2946971,127054,363146,2456858
28,Toledo,301969,21065,204,5336750,191823,6360892,278252,677493,5405590
29,Castilla y León,1233541,23119,2247,23388080,840127,28518841,1097107,3377824,24044772
30,Avila,75489,19975,248,1228668,46856,1507916,55776,155605,1296576
31,Burgos,193430,24552,371,3964539,115293,4749095,188163,589973,3971135
32,León,231436,22822,211,4345733,179222,5281751,211069,611921,4458913
33,Palencia,84680,22696,191,1570192,52591,1921871,75511,219529,1626865
34,Salamanca,164857,22478,362,2992789,104595,3705686,133001,437969,3134808
35,Segovia,75188,22481,209,1340157,48602,1690281,64725,194081,1431541
36,Soria,49213,22181,182,889585,24768,1091609,41772,124376,925494
37,Valladolid,274137,25169,225,5721630,216167,6899838,267853,873209,5758997
38,Zamora,85111,19631,248,1334786,52033,1670794,59239,171161,1440442
39,Cataluña,3502447,29541,942,81373366,3531896,103465362,3920939,15743600,83803975
40,Barcelona,2623187,30919,311,63510867,2825323,81106605,3017311,12760069,65331842
41,Girona,328059,26228,221,6702571,238349,8604283,351632,1169334,7083515
42,Lleida,198704,24110,226,3769632,165509,4790793,193195,613386,3984367
43,Tarragona,352497,25429,184,7390296,302715,8963681,358801,1200811,7404250
44,Extremadura,464536,19389,388,7299721,322637,9006991,334002,979363,7693790
45,Badajoz,282886,19478,165,4448771,196271,5509973,207423,596088,4706560
46,Cáceres,181650,19251,223,2850950,126366,3497018,126579,383275,2987230
47,Galicia,1276675,22762,313,23970309,865920,29060041,1125642,3627428,24308038
48,"Coruña, A",547104,24153,93,10937181,376857,13213975,512285,1753238,10948939
49,Lugo,160796,20429,67,2626988,113811,3284951,122599,375616,2786816