In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url1 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2022/jrubik7dee196ae088a75d2d7a295902b8c75056a9ed80.html"

response = requests.get(url)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df.to_csv("datos_irpf_provincia.csv_2022", index=False)

print(df.shape)
df.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_26792\1200132715.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,22898072,30400,7603,547838428,25700185,696112475,25763465,108398218,561969473
1,Andalucía,4092833,25203,785,81661113,4645442,103149809,3932732,13867280,85352146
2,Almería,370379,22508,103,6511399,331433,8336364,330075,1036104,6970325
3,Cádiz,562798,25902,45,11841966,698222,14577458,555339,1924752,12097599
4,Córdoba,386797,23546,77,7328856,379168,9107421,352350,1165906,7589325
5,Granada,453968,25024,174,8924832,558057,11360100,414651,1518147,9427495
6,Huelva,268057,22377,80,5068279,244080,5998219,249318,730729,5018280
7,Jaén,323032,21493,97,5607936,365708,6942831,258682,792642,5891679
8,Málaga,791650,27131,103,16058917,926204,21478629,791928,3039060,17648470
9,Sevilla,936152,27078,106,20318928,1142571,25348786,980388,3659939,20708973
10,Aragón,747459,29174,731,17655179,717741,21806342,842748,3291709,17672235
11,Huesca,121558,27781,202,2635395,109026,3376952,130060,482228,2764717
12,Teruel,72031,25682,236,1510493,58754,1849874,73824,248955,1527126
13,Zaragoza,553870,29934,293,13509291,549961,16579516,638863,2560526,13380393
14,"Asturias, Principado de",544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
15,Asturias,544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
16,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
17,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
18,Canarias,1040463,26500,88,21535915,963342,27572081,1065029,3554245,22954535
19,"Palmas, Las",544461,27060,34,11481846,543560,14733217,572533,1967217,12194739
20,Santa Cruz de Tenerife,496002,25885,54,10054068,419782,12838864,492497,1587028,10759795
21,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
22,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
23,Castilla y León,1315508,27356,2246,29201935,1189149,35987001,1320984,5039844,29626893
24,Avila,80053,24144,248,1558956,71083,1932799,70524,238982,1623345
25,Burgos,205370,29130,371,4932443,178043,5982494,226624,868355,4887599
26,León,243383,26701,211,5344112,237618,6498599,238078,891865,5368804
27,Palencia,88330,26402,191,1895077,77415,2332075,85654,313250,1933213
28,Salamanca,174762,26967,362,3702090,149438,4712850,163044,662486,3887400
29,Segovia,82253,26887,209,1751821,69042,2211575,83244,303954,1824414
30,Soria,51757,26737,181,1127809,39781,1383810,51700,188801,1143331
31,Valladolid,302270,29393,225,7242635,293518,8884645,330112,1318205,7236540
32,Zamora,87330,23453,248,1646990,73210,2048155,72004,253945,1722247
33,Castilla-La Mancha,1030479,25393,914,21588501,989807,26167274,1083948,3343501,21740330
34,Albacete,199723,25094,87,4104721,184155,5011761,205902,639396,4166552
35,Ciudad Real,235515,24721,102,4779965,240654,5822234,231121,739768,4851449
36,Cuenca,99738,23331,239,1871316,94728,2326948,90946,264820,1971219
37,Guadalajara,140128,28923,284,3427273,158208,4052946,172907,560977,3319137
38,Toledo,355375,25194,202,7405225,312063,8953384,383072,1138540,7431972
39,Cataluña,3993108,35030,947,108683103,5165970,139880270,5154746,24340491,110388501
40,Barcelona,2978835,36641,311,84467979,4071368,109148574,3953639,19581687,85616039
41,Girona,384384,31571,221,9247410,373933,12135294,464705,1939809,9731105
42,Lleida,221818,28986,231,5060641,243338,6429724,256820,965993,5207049
43,Tarragona,408071,29815,184,9907072,477332,12166679,479583,1853002,9834308
44,Comunitat Valenciana,2585870,27707,543,56338421,2719773,71646195,2793065,10474446,58380403
45,Alicante/Alacant,887100,25456,141,17536991,765091,22582352,882981,3094756,18605190
46,Castellón/Castelló,316860,27646,135,7039549,333177,8759797,352830,1277389,7129944
47,Valencia/València,1381910,29165,267,31761881,1621505,40304046,1557254,6102302,32645268
48,Extremadura,520184,22563,388,9433400,504250,11737158,432645,1472913,9831784
49,Badajoz,321207,22487,165,5790577,310879,7223016,270832,900895,6051401

In [6]:
url2 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2019/jrubikf75972228ea46b0ae33eab3856fdab1bf0228bd6f.html"

response = requests.get(url)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df.to_csv("datos_irpf_provincia_2019.csv", index=False)

print(df.shape)
df.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_26792\716885130.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,22898072,30400,7603,547838428,25700185,696112475,25763465,108398218,561969473
1,Andalucía,4092833,25203,785,81661113,4645442,103149809,3932732,13867280,85352146
2,Almería,370379,22508,103,6511399,331433,8336364,330075,1036104,6970325
3,Cádiz,562798,25902,45,11841966,698222,14577458,555339,1924752,12097599
4,Córdoba,386797,23546,77,7328856,379168,9107421,352350,1165906,7589325
5,Granada,453968,25024,174,8924832,558057,11360100,414651,1518147,9427495
6,Huelva,268057,22377,80,5068279,244080,5998219,249318,730729,5018280
7,Jaén,323032,21493,97,5607936,365708,6942831,258682,792642,5891679
8,Málaga,791650,27131,103,16058917,926204,21478629,791928,3039060,17648470
9,Sevilla,936152,27078,106,20318928,1142571,25348786,980388,3659939,20708973
10,Aragón,747459,29174,731,17655179,717741,21806342,842748,3291709,17672235
11,Huesca,121558,27781,202,2635395,109026,3376952,130060,482228,2764717
12,Teruel,72031,25682,236,1510493,58754,1849874,73824,248955,1527126
13,Zaragoza,553870,29934,293,13509291,549961,16579516,638863,2560526,13380393
14,"Asturias, Principado de",544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
15,Asturias,544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
16,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
17,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
18,Canarias,1040463,26500,88,21535915,963342,27572081,1065029,3554245,22954535
19,"Palmas, Las",544461,27060,34,11481846,543560,14733217,572533,1967217,12194739
20,Santa Cruz de Tenerife,496002,25885,54,10054068,419782,12838864,492497,1587028,10759795
21,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
22,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
23,Castilla y León,1315508,27356,2246,29201935,1189149,35987001,1320984,5039844,29626893
24,Avila,80053,24144,248,1558956,71083,1932799,70524,238982,1623345
25,Burgos,205370,29130,371,4932443,178043,5982494,226624,868355,4887599
26,León,243383,26701,211,5344112,237618,6498599,238078,891865,5368804
27,Palencia,88330,26402,191,1895077,77415,2332075,85654,313250,1933213
28,Salamanca,174762,26967,362,3702090,149438,4712850,163044,662486,3887400
29,Segovia,82253,26887,209,1751821,69042,2211575,83244,303954,1824414
30,Soria,51757,26737,181,1127809,39781,1383810,51700,188801,1143331
31,Valladolid,302270,29393,225,7242635,293518,8884645,330112,1318205,7236540
32,Zamora,87330,23453,248,1646990,73210,2048155,72004,253945,1722247
33,Castilla-La Mancha,1030479,25393,914,21588501,989807,26167274,1083948,3343501,21740330
34,Albacete,199723,25094,87,4104721,184155,5011761,205902,639396,4166552
35,Ciudad Real,235515,24721,102,4779965,240654,5822234,231121,739768,4851449
36,Cuenca,99738,23331,239,1871316,94728,2326948,90946,264820,1971219
37,Guadalajara,140128,28923,284,3427273,158208,4052946,172907,560977,3319137
38,Toledo,355375,25194,202,7405225,312063,8953384,383072,1138540,7431972
39,Cataluña,3993108,35030,947,108683103,5165970,139880270,5154746,24340491,110388501
40,Barcelona,2978835,36641,311,84467979,4071368,109148574,3953639,19581687,85616039
41,Girona,384384,31571,221,9247410,373933,12135294,464705,1939809,9731105
42,Lleida,221818,28986,231,5060641,243338,6429724,256820,965993,5207049
43,Tarragona,408071,29815,184,9907072,477332,12166679,479583,1853002,9834308
44,Comunitat Valenciana,2585870,27707,543,56338421,2719773,71646195,2793065,10474446,58380403
45,Alicante/Alacant,887100,25456,141,17536991,765091,22582352,882981,3094756,18605190
46,Castellón/Castelló,316860,27646,135,7039549,333177,8759797,352830,1277389,7129944
47,Valencia/València,1381910,29165,267,31761881,1621505,40304046,1557254,6102302,32645268
48,Extremadura,520184,22563,388,9433400,504250,11737158,432645,1472913,9831784
49,Badajoz,321207,22487,165,5790577,310879,7223016,270832,900895,6051401

In [7]:
url3 = "https://sede.agenciatributaria.gob.es/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Estadisticas/Publicaciones/sites/irpfmunicipios/2016/jrubik3f9f09f705d8c4130e1303e412a2dd0af62da913.html"

response = requests.get(url)
response.encoding = 'utf-8'  
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table')

df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

df.to_csv("datos_irpf_provincia_2016.csv", index=False)

print(df.shape)
df.head(50)

(68, 10)

C:\Users\Jon\AppData\Local\Temp\ipykernel_26792\386893499.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[0]), decimal=",", thousands=".")[0]

,Unnamed: 0,Número de declaraciones,Renta bruta media,Número de municipios,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de la autoliquidación,Renta disponible
0,Total,22898072,30400,7603,547838428,25700185,696112475,25763465,108398218,561969473
1,Andalucía,4092833,25203,785,81661113,4645442,103149809,3932732,13867280,85352146
2,Almería,370379,22508,103,6511399,331433,8336364,330075,1036104,6970325
3,Cádiz,562798,25902,45,11841966,698222,14577458,555339,1924752,12097599
4,Córdoba,386797,23546,77,7328856,379168,9107421,352350,1165906,7589325
5,Granada,453968,25024,174,8924832,558057,11360100,414651,1518147,9427495
6,Huelva,268057,22377,80,5068279,244080,5998219,249318,730729,5018280
7,Jaén,323032,21493,97,5607936,365708,6942831,258682,792642,5891679
8,Málaga,791650,27131,103,16058917,926204,21478629,791928,3039060,17648470
9,Sevilla,936152,27078,106,20318928,1142571,25348786,980388,3659939,20708973
10,Aragón,747459,29174,731,17655179,717741,21806342,842748,3291709,17672235
11,Huesca,121558,27781,202,2635395,109026,3376952,130060,482228,2764717
12,Teruel,72031,25682,236,1510493,58754,1849874,73824,248955,1527126
13,Zaragoza,553870,29934,293,13509291,549961,16579516,638863,2560526,13380393
14,"Asturias, Principado de",544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
15,Asturias,544015,29498,78,13080751,710379,16047490,573600,2378703,13095547
16,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
17,"Balears, Illes",596804,33006,67,13811818,522120,19697970,701511,3245740,15751061
18,Canarias,1040463,26500,88,21535915,963342,27572081,1065029,3554245,22954535
19,"Palmas, Las",544461,27060,34,11481846,543560,14733217,572533,1967217,12194739
20,Santa Cruz de Tenerife,496002,25885,54,10054068,419782,12838864,492497,1587028,10759795
21,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
22,Cantabria,311959,29166,102,7326796,311554,9098573,335914,1319543,7443353
23,Castilla y León,1315508,27356,2246,29201935,1189149,35987001,1320984,5039844,29626893
24,Avila,80053,24144,248,1558956,71083,1932799,70524,238982,1623345
25,Burgos,205370,29130,371,4932443,178043,5982494,226624,868355,4887599
26,León,243383,26701,211,5344112,237618,6498599,238078,891865,5368804
27,Palencia,88330,26402,191,1895077,77415,2332075,85654,313250,1933213
28,Salamanca,174762,26967,362,3702090,149438,4712850,163044,662486,3887400
29,Segovia,82253,26887,209,1751821,69042,2211575,83244,303954,1824414
30,Soria,51757,26737,181,1127809,39781,1383810,51700,188801,1143331
31,Valladolid,302270,29393,225,7242635,293518,8884645,330112,1318205,7236540
32,Zamora,87330,23453,248,1646990,73210,2048155,72004,253945,1722247
33,Castilla-La Mancha,1030479,25393,914,21588501,989807,26167274,1083948,3343501,21740330
34,Albacete,199723,25094,87,4104721,184155,5011761,205902,639396,4166552
35,Ciudad Real,235515,24721,102,4779965,240654,5822234,231121,739768,4851449
36,Cuenca,99738,23331,239,1871316,94728,2326948,90946,264820,1971219
37,Guadalajara,140128,28923,284,3427273,158208,4052946,172907,560977,3319137
38,Toledo,355375,25194,202,7405225,312063,8953384,383072,1138540,7431972
39,Cataluña,3993108,35030,947,108683103,5165970,139880270,5154746,24340491,110388501
40,Barcelona,2978835,36641,311,84467979,4071368,109148574,3953639,19581687,85616039
41,Girona,384384,31571,221,9247410,373933,12135294,464705,1939809,9731105
42,Lleida,221818,28986,231,5060641,243338,6429724,256820,965993,5207049
43,Tarragona,408071,29815,184,9907072,477332,12166679,479583,1853002,9834308
44,Comunitat Valenciana,2585870,27707,543,56338421,2719773,71646195,2793065,10474446,58380403
45,Alicante/Alacant,887100,25456,141,17536991,765091,22582352,882981,3094756,18605190
46,Castellón/Castelló,316860,27646,135,7039549,333177,8759797,352830,1277389,7129944
47,Valencia/València,1381910,29165,267,31761881,1621505,40304046,1557254,6102302,32645268
48,Extremadura,520184,22563,388,9433400,504250,11737158,432645,1472913,9831784
49,Badajoz,321207,22487,165,5790577,310879,7223016,270832,900895,6051401