In [87]:
import pandas as pd
import re

# 1. Cargar archivos
ruta1 = "Fuentes de datos demograficos - votos/2852.csv"
ruta2 = "Fuentes de datos demograficos - votos/68202.csv"

df_filtered = pd.read_csv(ruta1, sep=';', encoding='utf-8-sig', decimal=',')
df2 = pd.read_csv(ruta2, sep=';', encoding='latin1', decimal=',')

# 2. Limpiar nombres de columnas de ambos DataFrames
def limpiar_texto(texto):
    return re.sub(r"\d+", "", texto).strip()

for df in [df_filtered, df2]:
    if "Comunidades y Ciudades Autónomas" in df.columns:
        df["Comunidades y Ciudades Autónomas"] = df["Comunidades y Ciudades Autónomas"].apply(limpiar_texto)
    df["Provincias"] = df["Provincias"].apply(limpiar_texto)

# 3. Concatenar
df_combinado = pd.concat([df_filtered, df2], ignore_index=True)

# 4. Mostrar resultado
print(df_combinado.shape)
df_combinado.head(420)

(424, 4)

            Provincias   Sexo  Periodo       Total
0                Total  Total     2021  47.385.107
1                Total  Total     2020  47.450.795
2                Total  Total     2019  47.026.208
3                Total  Total     2018  46.722.980
4                Total  Total     2017  46.572.132
..                 ...    ...      ...         ...
415             Toledo  Total     2024     743.165
416  Valencia/València  Total     2024   2.710.808
417         Valladolid  Total     2024     525.116
418            Bizkaia  Total     2024   1.159.368
419             Zamora  Total     2024     166.253

[420 rows x 4 columns]

In [88]:
years_to_exclude = [2021, 2020, 2018, 2017, 2016]
df_filtered = df_combinado[~df_combinado['Periodo'].isin(years_to_exclude)]


print(df_filtered.shape)
df_filtered.head(50)

(159, 4)

             Provincias   Sexo  Periodo       Total
2                 Total  Total     2019  47.026.208
6                 Total  Total     2014  46.727.890
9              Albacete  Total     2019     388.167
13             Albacete  Total     2014     399.510
16     Alicante/Alacant  Total     2019   1.858.683
20     Alicante/Alacant  Total     2014   1.854.244
23              Almería  Total     2019     716.820
27              Almería  Total     2014     691.680
30          Araba/Álava  Total     2019     331.549
34          Araba/Álava  Total     2014     319.927
37             Asturias  Total     2019   1.022.800
41             Asturias  Total     2014   1.067.802
44                Ávila  Total     2019     157.640
48                Ávila  Total     2014     169.458
51              Badajoz  Total     2019     673.559
55              Badajoz  Total     2014     690.894
58       Balears, Illes  Total     2019   1.149.460
62       Balears, Illes  Total     2014   1.110.115
65            Barcelona  Total     2019   5.664.579
69            Barcelona  Total     2014   5.493.078
72              Bizkaia  Total     2019   1.152.651
76              Bizkaia  Total     2014   1.148.871
79               Burgos  Total     2019     356.958
83               Burgos  Total     2014     368.701
86              Cáceres  Total     2019     394.151
90              Cáceres  Total     2014     410.074
93                Cádiz  Total     2019   1.240.155
97                Cádiz  Total     2014   1.247.578
100           Cantabria  Total     2019     581.078
104           Cantabria  Total     2014     590.037
107  Castellón/Castelló  Total     2019     579.962
111  Castellón/Castelló  Total     2014     585.729
114         Ciudad Real  Total     2019     495.761
118         Ciudad Real  Total     2014     522.749
121             Córdoba  Total     2019     782.979
125             Córdoba  Total     2014     800.414
128           Coruña, A  Total     2019   1.119.596
132           Coruña, A  Total     2014   1.138.494
135              Cuenca  Total     2019     196.329
139              Cuenca  Total     2014     211.796
142            Gipuzkoa  Total     2019     723.576
146            Gipuzkoa  Total     2014     708.207
149              Girona  Total     2019     771.044
153              Girona  Total     2014     749.191
156             Granada  Total     2019     914.678
160             Granada  Total     2014     922.138
163         Guadalajara  Total     2019     257.762
167         Guadalajara  Total     2014     257.101
170              Huelva  Total     2019     521.870
174              Huelva  Total     2014     520.948

In [89]:
df_ordenado = df_filtered.sort_values(by=['Provincias', 'Periodo'], ascending=[True, False])

# Reiniciar los índices si quieres un índice limpio
df_ordenado.reset_index(drop=True, inplace=True)

# Mostrar resultado
df_ordenado.head(20)

          Provincias   Sexo  Periodo      Total
0           Albacete  Total     2024    389.070
1           Albacete  Total     2019    388.167
2           Albacete  Total     2014    399.510
3   Alicante/Alacant  Total     2024  1.993.289
4   Alicante/Alacant  Total     2019  1.858.683
5   Alicante/Alacant  Total     2014  1.854.244
6            Almería  Total     2024    760.964
7            Almería  Total     2019    716.820
8            Almería  Total     2014    691.680
9        Araba/Álava  Total     2024    338.594
10       Araba/Álava  Total     2019    331.549
11       Araba/Álava  Total     2014    319.927
12          Asturias  Total     2024  1.009.599
13          Asturias  Total     2019  1.022.800
14          Asturias  Total     2014  1.067.802
15           Badajoz  Total     2024    666.029
16           Badajoz  Total     2019    673.559
17           Badajoz  Total     2014    690.894
18    Balears, Illes  Total     2024  1.231.768
19    Balears, Illes  Total     2019  1.149.460

In [90]:
dict_provincia = {
    "Araba/Álava": 1,
    "Albacete": 2,
    "Alicante/Alacant": 3,
    "Almería": 4,
    "Ávila": 5,
    "Badajoz": 6,
    "Balears, Illes": 7,
    "Barcelona": 8,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Castellón/Castelló": 12,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "Coruña, A": 15,
    "Cuenca": 16,
    "Girona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Gipuzkoa": 20,
    "Huelva": 21,
    "Huesca": 22,
    "Jaén": 23,
    "León": 24,
    "Lleida": 25,
    "Rioja, La": 26,
    "Lugo": 27,
    "Madrid": 28,
    "Málaga": 29,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Asturias": 33,
    "Palencia": 34,
    "Palmas, Las": 35,
    "Pontevedra": 36,
    "Salamanca": 37,
    "Santa Cruz de Tenerife": 38,
    "Cantabria": 39,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia/València": 46,
    "Valladolid": 47,
    "Bizkaia": 48,
    "Zamora": 49,
    "Zaragoza": 50,
    "Ceuta": 51,
    "Melilla": 52,
}

# Aplicar el diccionario al DataFrame
df_ordenado["CodigoProvincia"] = df_ordenado["Provincias"].map(dict_provincia)
df_ordenado["CodigoProvincia"] = df_ordenado["CodigoProvincia"].fillna(0).astype(int)

df_ordenado.to_csv("datos_demograficos_codigo.csv", index=False)

# Verificamos
df_ordenado.head(50)

            Provincias   Sexo  Periodo      Total  CodigoProvincia
0             Albacete  Total     2024    389.070                2
1             Albacete  Total     2019    388.167                2
2             Albacete  Total     2014    399.510                2
3     Alicante/Alacant  Total     2024  1.993.289                3
4     Alicante/Alacant  Total     2019  1.858.683                3
5     Alicante/Alacant  Total     2014  1.854.244                3
6              Almería  Total     2024    760.964                4
7              Almería  Total     2019    716.820                4
8              Almería  Total     2014    691.680                4
9          Araba/Álava  Total     2024    338.594                1
10         Araba/Álava  Total     2019    331.549                1
11         Araba/Álava  Total     2014    319.927                1
12            Asturias  Total     2024  1.009.599               33
13            Asturias  Total     2019  1.022.800               33
14            Asturias  Total     2014  1.067.802               33
15             Badajoz  Total     2024    666.029                6
16             Badajoz  Total     2019    673.559                6
17             Badajoz  Total     2014    690.894                6
18      Balears, Illes  Total     2024  1.231.768                7
19      Balears, Illes  Total     2019  1.149.460                7
20      Balears, Illes  Total     2014  1.110.115                7
21           Barcelona  Total     2024  5.877.672                8
22           Barcelona  Total     2019  5.664.579                8
23           Barcelona  Total     2014  5.493.078                8
24             Bizkaia  Total     2024  1.159.368               48
25             Bizkaia  Total     2019  1.152.651               48
26             Bizkaia  Total     2014  1.148.871               48
27              Burgos  Total     2024    359.740                9
28              Burgos  Total     2019    356.958                9
29              Burgos  Total     2014    368.701                9
30           Cantabria  Total     2024    590.851               39
31           Cantabria  Total     2019    581.078               39
32           Cantabria  Total     2014    590.037               39
33  Castellón/Castelló  Total     2024    615.188               12
34  Castellón/Castelló  Total     2019    579.962               12
35  Castellón/Castelló  Total     2014    585.729               12
36               Ceuta  Total     2024     83.179               51
37               Ceuta  Total     2019     84.777               51
38               Ceuta  Total     2014     84.534               51
39         Ciudad Real  Total     2024    492.948               13
40         Ciudad Real  Total     2019    495.761               13
41         Ciudad Real  Total     2014    522.749               13
42           Coruña, A  Total     2024  1.128.449               15
43           Coruña, A  Total     2019  1.119.596               15
44           Coruña, A  Total     2014  1.138.494               15
45              Cuenca  Total     2024    199.025               16
46              Cuenca  Total     2019    196.329               16
47              Cuenca  Total     2014    211.796               16
48             Cáceres  Total     2024    388.652               10
49             Cáceres  Total     2019    394.151               10